/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("exercises").del();
  await knex("exercises").insert([
    {
      name: "Push-ups",
      calories_per_hour: 500,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 3,
      core: 3,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 1,
      balance: 2,
    },
    {
      name: "Swimming",
      calories_per_hour: 600,
      effort: 3,
      sport: true,
      upper_body: 4,
      lower_body: 4,
      full_body: 5,
      core: 4,
      arms: 4,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 4,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 4,
      balance: 3,
    },
    {
      name: "Running",
      calories_per_hour: 700,
      effort: 4,
      sport: true,
      upper_body: 1,
      lower_body: 5,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 5,
      glutes: 4,
      aerobic_cardio: 5,
      anaerobic_cardio: 3,
      strength: 2,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Pull-ups",
      calories_per_hour: 400,
      effort: 5,
      sport: false,
      upper_body: 5,
      lower_body: 1,
      full_body: 3,
      core: 4,
      arms: 5,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 5,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Squats",
      calories_per_hour: 400,
      effort: 4,
      sport: false,
      upper_body: 1,
      lower_body: 5,
      full_body: 4,
      core: 4,
      arms: 1,
      legs: 5,
      glutes: 5,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 4,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Glute Bridge",
      calories_per_hour: 300,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 2,
      core: 3,
      arms: 1,
      legs: 2,
      glutes: 5,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Split Squats",
      calories_per_hour: 450,
      effort: 4,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 4,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Walking Lunges",
      calories_per_hour: 400,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 3,
      anaerobic_cardio: 3,
      strength: 3,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Single Leg Deadlift",
      calories_per_hour: 350,
      effort: 4,
      sport: false,
      upper_body: 2,
      lower_body: 4,
      full_body: 3,
      core: 4,
      arms: 2,
      legs: 4,
      glutes: 5,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 4,
      flexibility: 3,
      balance: 5,
    },
    {
      name: "Goblet Squat",
      calories_per_hour: 420,
      effort: 4,
      sport: false,
      upper_body: 2,
      lower_body: 5,
      full_body: 4,
      core: 4,
      arms: 2,
      legs: 5,
      glutes: 5,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 4,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Front Squat",
      calories_per_hour: 450,
      effort: 5,
      sport: false,
      upper_body: 3,
      lower_body: 5,
      full_body: 4,
      core: 4,
      arms: 3,
      legs: 5,
      glutes: 5,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 5,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Calf Raises",
      calories_per_hour: 250,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 1,
      core: 1,
      arms: 1,
      legs: 3,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Kettlebell Swing",
      calories_per_hour: 600,
      effort: 4,
      sport: false,
      upper_body: 4,
      lower_body: 4,
      full_body: 5,
      core: 5,
      arms: 3,
      legs: 4,
      glutes: 5,
      aerobic_cardio: 3,
      anaerobic_cardio: 3,
      strength: 4,
      flexibility: 3,
      balance: 4,
    },
    {
      name: "Side Lunge",
      calories_per_hour: 380,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 3,
      flexibility: 3,
      balance: 4,
    },
    {
      name: "Leg Curl",
      calories_per_hour: 280,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 1,
      core: 1,
      arms: 1,
      legs: 4,
      glutes: 2,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Leg Extension",
      calories_per_hour: 280,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 1,
      core: 1,
      arms: 1,
      legs: 4,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 1,
      balance: 1,
    },
    {
      name: "Romanian Deadlift",
      calories_per_hour: 350,
      effort: 4,
      sport: false,
      upper_body: 2,
      lower_body: 5,
      full_body: 3,
      core: 4,
      arms: 2,
      legs: 4,
      glutes: 5,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 4,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Leg Press",
      calories_per_hour: 400,
      effort: 4,
      sport: false,
      upper_body: 1,
      lower_body: 5,
      full_body: 2,
      core: 3,
      arms: 1,
      legs: 5,
      glutes: 4,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 5,
      flexibility: 1,
      balance: 1,
    },
    {
      name: "Walking",
      calories_per_hour: 300,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 2,
      core: 2,
      arms: 1,
      legs: 3,
      glutes: 3,
      aerobic_cardio: 3,
      anaerobic_cardio: 1,
      strength: 1,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Curtsy Lunge",
      calories_per_hour: 400,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 5,
      aerobic_cardio: 2,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 3,
      balance: 4,
    },
    {
      name: "Squat Jump",
      calories_per_hour: 550,
      effort: 5,
      sport: false,
      upper_body: 1,
      lower_body: 5,
      full_body: 4,
      core: 4,
      arms: 1,
      legs: 5,
      glutes: 5,
      aerobic_cardio: 3,
      anaerobic_cardio: 4,
      strength: 4,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Side Leg Raises",
      calories_per_hour: 250,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 1,
      core: 2,
      arms: 1,
      legs: 3,
      glutes: 4,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Donkey Kicks",
      calories_per_hour: 280,
      effort: 2,
      sport: false,
      upper_body: 2,
      lower_body: 3,
      full_body: 2,
      core: 3,
      arms: 2,
      legs: 3,
      glutes: 5,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Wall Sit",
      calories_per_hour: 300,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 2,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 1,
      balance: 1,
    },
    {
      name: "Step-up",
      calories_per_hour: 350,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 2,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Hip Extension",
      calories_per_hour: 280,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 1,
      core: 2,
      arms: 1,
      legs: 3,
      glutes: 4,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Bicep Curl",
      calories_per_hour: 200,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Chest Press",
      calories_per_hour: 250,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 3,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Shoulder Press",
      calories_per_hour: 220,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 3,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Lateral Dumbbell Raises",
      calories_per_hour: 180,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 3,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Bent-over Rows",
      calories_per_hour: 300,
      effort: 3,
      sport: false,
      upper_body: 5,
      lower_body: 3,
      full_body: 4,
      core: 4,
      arms: 3,
      legs: 3,
      glutes: 3,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 4,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Triceps Kickbacks",
      calories_per_hour: 150,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Triceps Extensions",
      calories_per_hour: 170,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Tricep Dips",
      calories_per_hour: 280,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Close Grip Bench Press",
      calories_per_hour: 260,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Bench Press",
      calories_per_hour: 250,
      effort: 3,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 3,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Upright Row",
      calories_per_hour: 200,
      effort: 2,
      sport: false,
      upper_body: 4,
      lower_body: 1,
      full_body: 2,
      core: 2,
      arms: 3,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Arm Circles",
      calories_per_hour: 100,
      effort: 1,
      sport: false,
      upper_body: 2,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 2,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 1,
      flexibility: 3,
      balance: 1,
    },
    {
      name: "Plank",
      calories_per_hour: 150,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 4,
      core: 5,
      arms: 3,
      legs: 3,
      glutes: 3,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Skull Crusher",
      calories_per_hour: 160,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Cable Triceps Pushdown",
      calories_per_hour: 170,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 1,
      full_body: 1,
      core: 1,
      arms: 4,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Crunch",
      calories_per_hour: 120,
      effort: 2,
      sport: false,
      upper_body: 2,
      lower_body: 1,
      full_body: 2,
      core: 4,
      arms: 2,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Sit-up",
      calories_per_hour: 150,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 2,
      full_body: 3,
      core: 4,
      arms: 2,
      legs: 2,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 3,
      balance: 1,
    },
    {
      name: "Dead Bug",
      calories_per_hour: 100,
      effort: 2,
      sport: false,
      upper_body: 2,
      lower_body: 2,
      full_body: 3,
      core: 4,
      arms: 2,
      legs: 2,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Russian Twist",
      calories_per_hour: 180,
      effort: 3,
      sport: false,
      upper_body: 2,
      lower_body: 2,
      full_body: 3,
      core: 5,
      arms: 2,
      legs: 2,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Bicycle Crunch",
      calories_per_hour: 200,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 4,
      core: 5,
      arms: 2,
      legs: 3,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Leg Raises",
      calories_per_hour: 150,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 2,
      core: 4,
      arms: 1,
      legs: 4,
      glutes: 2,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "V-Sit",
      calories_per_hour: 180,
      effort: 4,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 4,
      core: 5,
      arms: 2,
      legs: 3,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Superman",
      calories_per_hour: 120,
      effort: 2,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 3,
      core: 3,
      arms: 2,
      legs: 3,
      glutes: 3,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 3,
      balance: 2,
    },
    {
      name: "Flutter Kicks",
      calories_per_hour: 160,
      effort: 3,
      sport: false,
      upper_body: 2,
      lower_body: 4,
      full_body: 3,
      core: 4,
      arms: 2,
      legs: 4,
      glutes: 2,
      aerobic_cardio: 1,
      anaerobic_cardio: 2,
      strength: 3,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Side Plank",
      calories_per_hour: 130,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 4,
      core: 5,
      arms: 3,
      legs: 3,
      glutes: 3,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Oblique Crunch",
      calories_per_hour: 130,
      effort: 2,
      sport: false,
      upper_body: 2,
      lower_body: 1,
      full_body: 2,
      core: 4,
      arms: 2,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Suitcase Crunch",
      calories_per_hour: 160,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 3,
      full_body: 4,
      core: 5,
      arms: 2,
      legs: 3,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Penguin Crunch",
      calories_per_hour: 110,
      effort: 2,
      sport: false,
      upper_body: 2,
      lower_body: 1,
      full_body: 2,
      core: 4,
      arms: 2,
      legs: 1,
      glutes: 1,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 2,
      flexibility: 2,
      balance: 1,
    },
    {
      name: "Tennis",
      calories_per_hour: 500,
      effort: 4,
      sport: true,
      upper_body: 3,
      lower_body: 4,
      full_body: 5,
      core: 4,
      arms: 3,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 4,
      anaerobic_cardio: 4,
      strength: 3,
      flexibility: 4,
      balance: 5,
    },
    {
      name: "Volleyball",
      calories_per_hour: 400,
      effort: 3,
      sport: true,
      upper_body: 4,
      lower_body: 4,
      full_body: 5,
      core: 4,
      arms: 4,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 3,
      anaerobic_cardio: 4,
      strength: 3,
      flexibility: 3,
      balance: 4,
    },
    {
      name: "Table Tennis",
      calories_per_hour: 250,
      effort: 2,
      sport: true,
      upper_body: 3,
      lower_body: 2,
      full_body: 3,
      core: 2,
      arms: 3,
      legs: 2,
      glutes: 2,
      aerobic_cardio: 2,
      anaerobic_cardio: 3,
      strength: 2,
      flexibility: 3,
      balance: 4,
    },
    {
      name: "Surfing",
      calories_per_hour: 300,
      effort: 3,
      sport: true,
      upper_body: 3,
      lower_body: 4,
      full_body: 5,
      core: 5,
      arms: 3,
      legs: 4,
      glutes: 4,
      aerobic_cardio: 3,
      anaerobic_cardio: 3,
      strength: 3,
      flexibility: 3,
      balance: 5,
    },
    {
      name: "Elliptical",
      calories_per_hour: 400,
      effort: 3,
      sport: false,
      upper_body: 3,
      lower_body: 4,
      full_body: 4,
      core: 3,
      arms: 3,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 4,
      anaerobic_cardio: 2,
      strength: 2,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Stair Climber",
      calories_per_hour: 500,
      effort: 4,
      sport: false,
      upper_body: 1,
      lower_body: 5,
      full_body: 3,
      core: 3,
      arms: 1,
      legs: 5,
      glutes: 4,
      aerobic_cardio: 4,
      anaerobic_cardio: 3,
      strength: 3,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Stationary Bike",
      calories_per_hour: 350,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 4,
      full_body: 2,
      core: 2,
      arms: 1,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 4,
      anaerobic_cardio: 2,
      strength: 2,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Biking",
      calories_per_hour: 450,
      effort: 3,
      sport: true,
      upper_body: 2,
      lower_body: 4,
      full_body: 3,
      core: 3,
      arms: 2,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 4,
      anaerobic_cardio: 3,
      strength: 2,
      flexibility: 2,
      balance: 3,
    },
    {
      name: "Indoor Rower",
      calories_per_hour: 600,
      effort: 4,
      sport: false,
      upper_body: 4,
      lower_body: 4,
      full_body: 5,
      core: 5,
      arms: 4,
      legs: 4,
      glutes: 3,
      aerobic_cardio: 4,
      anaerobic_cardio: 3,
      strength: 4,
      flexibility: 3,
      balance: 3,
    },
    {
      name: "Jacob's Ladder",
      calories_per_hour: 550,
      effort: 4,
      sport: false,
      upper_body: 3,
      lower_body: 5,
      full_body: 5,
      core: 4,
      arms: 3,
      legs: 5,
      glutes: 4,
      aerobic_cardio: 5,
      anaerobic_cardio: 4,
      strength: 3,
      flexibility: 2,
      balance: 4,
    },
    {
      name: "Hip Thrusts",
      calories_per_hour: 300,
      effort: 3,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 2,
      core: 3,
      arms: 1,
      legs: 2,
      glutes: 5,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 4,
      flexibility: 2,
      balance: 2,
    },
    {
      name: "Adductor Machine",
      calories_per_hour: 200,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 1,
      core: 1,
      arms: 1,
      legs: 3,
      glutes: 2,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 3,
      balance: 1,
    },
    {
      name: "Abductor Machine",
      calories_per_hour: 200,
      effort: 2,
      sport: false,
      upper_body: 1,
      lower_body: 3,
      full_body: 1,
      core: 1,
      arms: 1,
      legs: 3,
      glutes: 4,
      aerobic_cardio: 1,
      anaerobic_cardio: 1,
      strength: 3,
      flexibility: 3,
      balance: 1,
    },
  ]);
};
